version: '3'

services:
  app:
    build:
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app     
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh
    command: sh -c "npm install && node server.js"
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
 
networks:
  node-network:
    driver: bridge